package com.emre.gunumplanner

import android.Manifest
import android.app.Activity
import android.app.DatePickerDialog
import android.app.TimePickerDialog
import android.content.ActivityNotFoundException
import android.content.Intent
import android.content.pm.PackageManager
import android.os.Build
import android.os.Bundle
import android.speech.RecognizerIntent
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.LazyListScope
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.rounded.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import java.time.*
import java.time.format.DateTimeFormatter
import java.time.format.TextStyle
import java.util.Locale

class PremiumMainActivity : ComponentActivity() {
    lateinit var db: Db
    private var voiceResult: ((String) -> Unit)? = null
    private val voiceLauncher = registerForActivityResult(ActivityResultContracts.StartActivityForResult()) { r ->
        if (r.resultCode == Activity.RESULT_OK) {
            val text = r.data?.getStringArrayListExtra(RecognizerIntent.EXTRA_RESULTS)?.firstOrNull().orEmpty()
            if (text.isNotBlank()) voiceResult?.invoke(text.trim())
        }
    }
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState); db = Db(this); askNotifications()
        setContent { PremiumTheme { PlannerApp(this, db) } }
    }
    fun voice(cb: (String) -> Unit) {
        voiceResult = cb
        val i = Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH).apply {
            putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL, RecognizerIntent.LANGUAGE_MODEL_FREE_FORM)
            putExtra(RecognizerIntent.EXTRA_LANGUAGE, "tr-TR")
        }
        try { voiceLauncher.launch(i) } catch (_: ActivityNotFoundException) {}
    }
    fun pickDate(d: LocalDate, cb: (LocalDate) -> Unit) = DatePickerDialog(this,{_,y,m,dd->cb(LocalDate.of(y,m+1,dd))},d.year,d.monthValue-1,d.dayOfMonth).show()
    fun pickTime(t: LocalTime, cb: (LocalTime) -> Unit) = TimePickerDialog(this,{_,h,m->cb(LocalTime.of(h,m))},t.hour,t.minute,true).show()
    private fun askNotifications(){ if(Build.VERSION.SDK_INT>=33 && checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED) requestPermissions(arrayOf(Manifest.permission.POST_NOTIFICATIONS),901) }
}

private val Light = lightColorScheme(
    primary=Color(0xFF4B57E8), onPrimary=Color.White, primaryContainer=Color(0xFFE8EAFF),
    secondary=Color(0xFF7259D8), secondaryContainer=Color(0xFFEEE9FF),
    background=Color(0xFFF7F8FC), surface=Color.White, surfaceVariant=Color(0xFFF0F2F8),
    onSurface=Color(0xFF191B24), onSurfaceVariant=Color(0xFF697080), outline=Color(0xFFD9DDE8)
)
private val Dark = darkColorScheme(
    primary=Color(0xFFBBC2FF), onPrimary=Color(0xFF1C276E), primaryContainer=Color(0xFF303B8B),
    secondary=Color(0xFFD1C7FF), secondaryContainer=Color(0xFF493C8A),
    background=Color(0xFF0F1116), surface=Color(0xFF17191F), surfaceVariant=Color(0xFF232630),
    onSurface=Color(0xFFF4F4F7), onSurfaceVariant=Color(0xFFB5B9C5), outline=Color(0xFF3C404B)
)
@Composable fun PremiumTheme(c:@Composable()->Unit){ MaterialTheme(colorScheme=if(androidx.compose.foundation.isSystemInDarkTheme()) Dark else Light, shapes=Shapes(small=RoundedCornerShape(12.dp),medium=RoundedCornerShape(20.dp),large=RoundedCornerShape(28.dp)),content=c) }

enum class PScreen{TODAY,HISTORY,TOPICS,SEARCH,TOPIC}

@OptIn(ExperimentalMaterial3Api::class)
@Composable fun PlannerApp(a:PremiumMainActivity, db:Db){
    var screen by rememberSaveable{ mutableStateOf(PScreen.TODAY) }
    var dateText by rememberSaveable{ mutableStateOf(LocalDate.now().toString()) }
    var topicId by rememberSaveable{ mutableStateOf(0L) }
    var query by rememberSaveable{ mutableStateOf("") }
    var rev by remember{ mutableIntStateOf(0) }
    var add by remember{ mutableStateOf(false) }; var taskEdit by remember{ mutableStateOf<Db.Item?>(null) }; var noteEdit by remember{ mutableStateOf<Db.Item?>(null) }
    var showTask by remember{ mutableStateOf(false) }; var showNote by remember{ mutableStateOf(false) }; var showQuick by remember{ mutableStateOf(false) }; var chosen by remember{ mutableStateOf<Db.Item?>(null) }
    val d=runCatching{LocalDate.parse(dateText)}.getOrDefault(LocalDate.now())
    val dayItems=remember(screen,dateText,rev){ if(screen==PScreen.TODAY) db.getItemsForDay(dateText) else emptyList() }
    val stats=remember(screen,dateText,rev){ db.getDayStats(dateText) }
    val events=remember(screen,dateText,rev){ if(screen==PScreen.HISTORY) db.getEventsForDay(dateText) else emptyList() }
    val topics=remember(screen,rev){ if(screen==PScreen.TOPICS||screen==PScreen.TOPIC) db.getTopics() else emptyList() }
    val topicItems=remember(screen,topicId,rev){ if(screen==PScreen.TOPIC) db.getItemsForTopic(topicId) else emptyList() }
    val results=remember(screen,query,rev){ if(screen==PScreen.SEARCH&&query.isNotBlank()) db.searchItems(query) else emptyList() }
    fun refresh(){rev++}

    Scaffold(
        containerColor=MaterialTheme.colorScheme.background,
        topBar={ PremiumTop(screen,d,if(screen==PScreen.TOPIC)db.getTopic(topicId) else null){screen=PScreen.TOPICS} },
        bottomBar={ NavigationBar(containerColor=MaterialTheme.colorScheme.surface){
            nav(Icons.Rounded.Home,"Bugün",screen==PScreen.TODAY){screen=PScreen.TODAY;dateText=LocalDate.now().toString()}
            nav(Icons.Rounded.CalendarMonth,"Geçmiş",screen==PScreen.HISTORY){screen=PScreen.HISTORY}
            nav(Icons.Rounded.Folder,"Konular",screen==PScreen.TOPICS||screen==PScreen.TOPIC){screen=PScreen.TOPICS}
            nav(Icons.Rounded.Search,"Ara",screen==PScreen.SEARCH){screen=PScreen.SEARCH}
        }},
        floatingActionButton={ ExtendedFloatingActionButton(onClick={add=true},icon={Icon(Icons.Rounded.Add,null)},text={Text("Ekle",fontWeight=FontWeight.SemiBold)}) }
    ){pad->
        when(screen){
            PScreen.TODAY->TodayPage(d,stats,dayItems,{dateText=it.toString()},{a.pickDate(d){dateText=it.toString()}},{chosen=it},{item->
                if(item.status==Db.STATUS_DONE)db.reopenItem(item.id) else { val n=db.completeItem(item.id); ReminderScheduler.cancel(a,item.id); if(n>0) db.getItem(n)?.let{if(it.dueAt>System.currentTimeMillis())ReminderScheduler.schedule(a,it.id,it.dueAt)} };refresh()
            },{ a.voice{text-> val p=NaturalLanguageParser.parse(text,d); val t=TopicEngine.findMatchingTopic(db,p.title,p.original); val id=db.insertItem(Db.TYPE_TASK,p.title,"",p.dayKey,p.dueAt,t,p.recurrence,p.durationMinutes,p.priority);if(p.dueAt>0)ReminderScheduler.schedule(a,id,p.dueAt);dateText=p.dayKey;refresh()} },{
                val plan=SmartPlanner.propose(db.getOpenTasksUpTo(LocalDate.now().toString()),LocalDate.now()); plan.forEach{ReminderScheduler.cancel(a,it.itemId);db.rescheduleItem(it.itemId,it.newDayKey,it.newDueAt);ReminderScheduler.schedule(a,it.itemId,it.newDueAt)};dateText=LocalDate.now().toString();refresh()
            },Modifier.padding(pad))
            PScreen.HISTORY->HistoryPage(d,stats,events,{dateText=it.toString()},{a.pickDate(d){dateText=it.toString()}},Modifier.padding(pad))
            PScreen.TOPICS->TopicsPage(topics,db,{topicId=it;screen=PScreen.TOPIC},Modifier.padding(pad))
            PScreen.TOPIC->TopicPage(db.getTopic(topicId),topicItems,{chosen=it},Modifier.padding(pad))
            PScreen.SEARCH->SearchPage(query,{query=it},results,{chosen=it},Modifier.padding(pad))
        }
    }

    if(add) AddSheet({add=false},{add=false;showQuick=true},{add=false;taskEdit=null;showTask=true},{add=false;noteEdit=null;showNote=true},{add=false;a.voice{text->val p=NaturalLanguageParser.parse(text,d);val t=TopicEngine.findMatchingTopic(db,p.title,p.original);val id=db.insertItem(Db.TYPE_TASK,p.title,"",p.dayKey,p.dueAt,t,p.recurrence,p.durationMinutes,p.priority);if(p.dueAt>0)ReminderScheduler.schedule(a,id,p.dueAt);dateText=p.dayKey;refresh()}},{add=false;a.voice{text->val title=TopicEngine.suggestTitle(text);val t=if(screen==PScreen.TOPIC)topicId else TopicEngine.findOrCreateTopic(db,title,text);db.insertItem(Db.TYPE_NOTE,title,text,LocalDate.now().toString(),0,t);TopicEngine.refreshAutoTitle(db,t);refresh()}})
    if(showQuick) QuickDialog(d,{showQuick=false}){p->val t=TopicEngine.findMatchingTopic(db,p.title,p.original);val id=db.insertItem(Db.TYPE_TASK,p.title,"",p.dayKey,p.dueAt,t,p.recurrence,p.durationMinutes,p.priority);if(p.dueAt>0)ReminderScheduler.schedule(a,id,p.dueAt);dateText=p.dayKey;showQuick=false;refresh()}
    if(showTask) TaskDialog(taskEdit,d,a,{showTask=false}){title,body,day,time,dur,rec,pri->val due=if(time==null)0L else LocalDateTime.of(day,time).atZone(ZoneId.systemDefault()).toInstant().toEpochMilli();val old=taskEdit;if(old==null){val t=TopicEngine.findMatchingTopic(db,title,body);val id=db.insertItem(Db.TYPE_TASK,title,body,day.toString(),due,t,rec,dur,pri);if(due>0)ReminderScheduler.schedule(a,id,due)}else{ReminderScheduler.cancel(a,old.id);db.updateItem(old.id,title,body,day.toString(),due,old.topicId,rec,dur,pri);if(due>0&&old.status==Db.STATUS_OPEN)ReminderScheduler.schedule(a,old.id,due)};dateText=day.toString();showTask=false;refresh()}
    if(showNote) NoteDialog(noteEdit,{showNote=false}){title0,body->val title=title0.ifBlank{TopicEngine.suggestTitle(body)};val old=noteEdit;if(old==null){val t=if(screen==PScreen.TOPIC)topicId else TopicEngine.findOrCreateTopic(db,title,body);db.insertItem(Db.TYPE_NOTE,title,body,LocalDate.now().toString(),0,t);TopicEngine.refreshAutoTitle(db,t)}else{db.updateItem(old.id,title,body,old.dayKey,0,old.topicId,"",0,2)};showNote=false;refresh()}
    chosen?.let{item->ItemSheet(item,{chosen=null},{if(item.status==Db.STATUS_DONE)db.reopenItem(item.id) else db.completeItem(item.id);ReminderScheduler.cancel(a,item.id);chosen=null;refresh()},{val nd=LocalDate.parse(item.dayKey).plusDays(1);val due=if(item.dueAt>0){val t=Instant.ofEpochMilli(item.dueAt).atZone(ZoneId.systemDefault()).toLocalTime();LocalDateTime.of(nd,t).atZone(ZoneId.systemDefault()).toInstant().toEpochMilli()}else 0;db.postponeItem(item.id,nd.toString(),due);if(due>0)ReminderScheduler.schedule(a,item.id,due);chosen=null;refresh()},{chosen=null;if(item.type==Db.TYPE_NOTE){noteEdit=item;showNote=true}else{taskEdit=item;showTask=true}},{ReminderScheduler.cancel(a,item.id);db.deleteItem(item.id);chosen=null;refresh()})}
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable fun PremiumTop(s:PScreen,d:LocalDate,t:Db.Topic?,back:()->Unit){ val title=when(s){PScreen.TODAY->if(d==LocalDate.now())"Bugün" else d.format(DateTimeFormatter.ofPattern("d MMMM",Locale("tr","TR")));PScreen.HISTORY->"Geçmiş";PScreen.TOPICS->"Konular";PScreen.SEARCH->"Arama";PScreen.TOPIC->t?.title?:"Konu"}; CenterAlignedTopAppBar(title={Column(horizontalAlignment=Alignment.CenterHorizontally){Text(title,fontWeight=FontWeight.SemiBold,maxLines=1,overflow=TextOverflow.Ellipsis);if(s==PScreen.TODAY)Text(d.dayOfWeek.getDisplayName(TextStyle.FULL,Locale("tr","TR")),style=MaterialTheme.typography.labelSmall,color=MaterialTheme.colorScheme.onSurfaceVariant)}},navigationIcon={if(s==PScreen.TOPIC)IconButton(onClick=back){Icon(Icons.Rounded.ArrowBack,null)}}) }
@Composable fun RowScope.nav(i:ImageVector,l:String,sel:Boolean,on:()->Unit){NavigationBarItem(sel,on,{Icon(i,l)},label={Text(l)},colors=NavigationBarItemDefaults.colors(indicatorColor=MaterialTheme.colorScheme.primaryContainer,selectedIconColor=MaterialTheme.colorScheme.primary))}

@Composable fun TodayPage(d:LocalDate,st:Db.DayStats,data:List<Db.Item>,date:(LocalDate)->Unit,pick:()->Unit,open:(Db.Item)->Unit,toggle:(Db.Item)->Unit,voice:()->Unit,plan:()->Unit,m:Modifier){val tasks=data.filter{it.type==Db.TYPE_TASK};val notes=data.filter{it.type==Db.TYPE_NOTE};val active=tasks.filter{it.status==Db.STATUS_OPEN};val next=active.filter{it.dueAt>0}.minByOrNull{it.dueAt}?:active.firstOrNull();val total=st.open+st.done;val pr=if(total==0)0f else st.done.toFloat()/total;LazyColumn(m.fillMaxSize(),contentPadding=PaddingValues(18.dp,8.dp,18.dp,116.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){item{DateStrip(d,date,pick)};item{Hero(st,pr)};if(next!=null)item{FocusCard(next,open)};item{LazyRow(horizontalArrangement=Arrangement.spacedBy(8.dp)){item{AssistChip(onClick=voice,label={Text("Sesle ekle")},leadingIcon={Icon(Icons.Rounded.KeyboardVoice,null,Modifier.size(18.dp))},colors=AssistChipDefaults.assistChipColors(containerColor=MaterialTheme.colorScheme.surface))};item{AssistChip(onClick=plan,label={Text("Akıllı plan")},leadingIcon={Icon(Icons.Rounded.AutoAwesome,null,Modifier.size(18.dp))},colors=AssistChipDefaults.assistChipColors(containerColor=MaterialTheme.colorScheme.surface))}}};item{Section("Bugünün planı",if(tasks.isEmpty())"Boş" else "${tasks.size} görev")};if(tasks.isEmpty())item{Empty("Günün boş görünüyor","İlk görevini ekle. Gün ilerledikçe gerektiği kadar eklemek daha gerçekçi bir plan sağlar.")}else items(tasks,key={it.id}){TaskCard(it,open,toggle)};if(notes.isNotEmpty()){item{Section("Notlar","${notes.size} kayıt")};items(notes,key={it.id}){NoteCard(it,open)}}}}
@Composable fun DateStrip(d:LocalDate,change:(LocalDate)->Unit,pick:()->Unit){val start=d.minusDays(3);Row(verticalAlignment=Alignment.CenterVertically){LazyRow(Modifier.weight(1f),horizontalArrangement=Arrangement.spacedBy(8.dp)){items((0..6).map{start.plusDays(it.toLong())}){x->val a=x==d;Surface(onClick={change(x)},shape=RoundedCornerShape(18.dp),color=if(a)MaterialTheme.colorScheme.primary else MaterialTheme.colorScheme.surface,contentColor=if(a)MaterialTheme.colorScheme.onPrimary else MaterialTheme.colorScheme.onSurface,modifier=Modifier.width(58.dp)){Column(Modifier.padding(vertical=10.dp),horizontalAlignment=Alignment.CenterHorizontally){Text(x.dayOfWeek.getDisplayName(TextStyle.SHORT,Locale("tr","TR")).uppercase(Locale("tr","TR")),style=MaterialTheme.typography.labelSmall);Text("${x.dayOfMonth}",style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.Bold)}}}};Spacer(Modifier.width(8.dp));IconButton(pick,Modifier.background(MaterialTheme.colorScheme.surface,CircleShape)){Icon(Icons.Rounded.CalendarMonth,null)}}}
@Composable fun Hero(s:Db.DayStats,p:Float){Card(shape=RoundedCornerShape(28.dp),colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surface)){Column(Modifier.padding(20.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){Row(verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text("Günün dengesi",color=MaterialTheme.colorScheme.primary,fontWeight=FontWeight.SemiBold);Text(if(s.open==0&&s.done>0)"Plan tamamlandı" else if(s.open>=6)"Yoğun bir gün" else "Kontrol sende",style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.Bold)};Text("%${(p*100).toInt()}",style=MaterialTheme.typography.titleLarge,color=MaterialTheme.colorScheme.primary)};LinearProgressIndicator(progress={p},modifier=Modifier.fillMaxWidth().height(8.dp).clip(CircleShape));Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){pill("${s.open} açık",MaterialTheme.colorScheme.primaryContainer,MaterialTheme.colorScheme.onPrimaryContainer);pill("${s.done} tamam",Color(0xFFE5F7ED),Color(0xFF176A44));pill("${s.notes} not",Color(0xFFFFF1D1),Color(0xFF8C5700))}}}}
@Composable fun pill(t:String,b:Color,f:Color){Surface(shape=CircleShape,color=b,contentColor=f){Text(t,Modifier.padding(horizontal=10.dp,vertical=7.dp),style=MaterialTheme.typography.labelMedium,fontWeight=FontWeight.SemiBold)}}
@Composable fun FocusCard(i:Db.Item,open:(Db.Item)->Unit){Card(onClick={open(i)},shape=RoundedCornerShape(28.dp),colors=CardDefaults.cardColors(containerColor=Color.Transparent)){Box(Modifier.fillMaxWidth().background(Brush.linearGradient(listOf(Color(0xFF202755),Color(0xFF4B56D8),Color(0xFF7568E8))),RoundedCornerShape(28.dp)).padding(20.dp)){Column(verticalArrangement=Arrangement.spacedBy(10.dp)){Row{Surface(color=Color.White.copy(alpha=.14f),shape=CircleShape){Text("ŞİMDİ",Modifier.padding(horizontal=10.dp,vertical=6.dp),color=Color.White,fontWeight=FontWeight.Bold,style=MaterialTheme.typography.labelSmall)};Spacer(Modifier.weight(1f));if(i.dueAt>0)Text(time(i.dueAt),color=Color.White.copy(alpha=.8f))};Text(i.title,color=Color.White,style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold,maxLines=2,overflow=TextOverflow.Ellipsis);Row(horizontalArrangement=Arrangement.spacedBy(12.dp)){if(i.durationMinutes>0)Text("${i.durationMinutes} dk",color=Color.White.copy(alpha=.8f));if(i.recurrence.isNotBlank())Text(NaturalLanguageParser.recurrenceLabel(i.recurrence),color=Color.White.copy(alpha=.8f))}}}}}
@Composable fun Section(a:String,b:String){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.Bottom){Text(a,style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold);Spacer(Modifier.weight(1f));Text(b,color=MaterialTheme.colorScheme.onSurfaceVariant,style=MaterialTheme.typography.labelMedium)}}
@Composable fun TaskCard(i:Db.Item,open:(Db.Item)->Unit,toggle:(Db.Item)->Unit){val done=i.status==Db.STATUS_DONE;Row(Modifier.fillMaxWidth()){Text(if(i.dueAt>0)time(i.dueAt) else "—",Modifier.width(48.dp).padding(top=16.dp),style=MaterialTheme.typography.labelMedium,color=MaterialTheme.colorScheme.onSurfaceVariant);Spacer(Modifier.width(10.dp));Column(horizontalAlignment=Alignment.CenterHorizontally){Box(Modifier.padding(top=18.dp).size(11.dp).background(if(done)Color(0xFF24A66A)else priority(i.priority),CircleShape));Box(Modifier.width(2.dp).height(76.dp).background(MaterialTheme.colorScheme.outline.copy(alpha=.5f)))};Spacer(Modifier.width(10.dp));Card(onClick={open(i)},shape=RoundedCornerShape(22.dp),colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surface),modifier=Modifier.weight(1f)){Row(Modifier.padding(15.dp),verticalAlignment=Alignment.Top){IconButton({toggle(i)},Modifier.size(34.dp)){Icon(if(done)Icons.Rounded.CheckCircle else Icons.Rounded.RadioButtonUnchecked,null,tint=if(done)Color(0xFF24A66A)else priority(i.priority))};Spacer(Modifier.width(8.dp));Column(Modifier.weight(1f)){Text(i.title,style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.SemiBold,maxLines=2,overflow=TextOverflow.Ellipsis);if(i.body.isNotBlank())Text(i.body,color=MaterialTheme.colorScheme.onSurfaceVariant,style=MaterialTheme.typography.bodySmall,maxLines=2,overflow=TextOverflow.Ellipsis);Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){if(i.durationMinutes>0)Text("${i.durationMinutes} dk",style=MaterialTheme.typography.labelSmall,color=MaterialTheme.colorScheme.onSurfaceVariant);if(i.priority<2)Text(if(i.priority==0)"Acil" else "Önemli",style=MaterialTheme.typography.labelSmall,color=priority(i.priority))}}}}}}
@Composable fun NoteCard(i:Db.Item,open:(Db.Item)->Unit){Surface(onClick={open(i)},shape=RoundedCornerShape(22.dp),color=Color(0xFFFFFBF2)){Row(Modifier.padding(16.dp)){Surface(shape=RoundedCornerShape(12.dp),color=Color(0xFFFFE9B5)){Icon(Icons.Rounded.Notes,null,Modifier.padding(9.dp).size(20.dp),tint=Color(0xFF8A5700))};Spacer(Modifier.width(12.dp));Column{Text(i.title,fontWeight=FontWeight.SemiBold,color=Color(0xFF372B13));if(i.body.isNotBlank())Text(i.body,color=Color(0xFF6E6045),maxLines=3,overflow=TextOverflow.Ellipsis)}}}}
@Composable fun Empty(a:String,b:String){Surface(shape=RoundedCornerShape(24.dp),color=MaterialTheme.colorScheme.surfaceVariant.copy(alpha=.7f)){Column(Modifier.padding(22.dp)){Text(a,fontWeight=FontWeight.SemiBold);Spacer(Modifier.height(4.dp));Text(b,color=MaterialTheme.colorScheme.onSurfaceVariant)}}}

@Composable fun HistoryPage(d:LocalDate,s:Db.DayStats,e:List<Db.Event>,change:(LocalDate)->Unit,pick:()->Unit,m:Modifier){LazyColumn(m.fillMaxSize(),contentPadding=PaddingValues(18.dp,8.dp,18.dp,116.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){item{DateStrip(d,change,pick)};item{Hero(s,if(s.open+s.done==0)0f else s.done.toFloat()/(s.open+s.done))};item{Section("Hareket günlüğü","${e.size} kayıt")};if(e.isEmpty())item{Empty("Bu gün sakin geçmiş","Oluşturma, tamamlama veya erteleme hareketi görünmüyor.")}else items(e,key={it.id}){x->Row{Text(Instant.ofEpochMilli(x.createdAt).atZone(ZoneId.systemDefault()).toLocalTime().format(DateTimeFormatter.ofPattern("HH:mm")),Modifier.width(52.dp),color=MaterialTheme.colorScheme.onSurfaceVariant);Spacer(Modifier.width(10.dp));Surface(shape=RoundedCornerShape(18.dp),color=MaterialTheme.colorScheme.surface,modifier=Modifier.weight(1f)){Column(Modifier.padding(14.dp)){Text(event(x.eventType),color=eventColor(x.eventType),fontWeight=FontWeight.Bold,style=MaterialTheme.typography.labelMedium);Text(x.titleSnapshot,fontWeight=FontWeight.SemiBold);if(x.details.isNotBlank())Text(x.details,color=MaterialTheme.colorScheme.onSurfaceVariant,style=MaterialTheme.typography.bodySmall)}}}}}}
@Composable fun TopicsPage(t:List<Db.Topic>,db:Db,open:(Long)->Unit,m:Modifier){LazyColumn(m.fillMaxSize(),contentPadding=PaddingValues(18.dp,8.dp,18.dp,116.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Surface(shape=RoundedCornerShape(26.dp),color=MaterialTheme.colorScheme.secondaryContainer){Column(Modifier.padding(20.dp)){Text("Konu hafızası",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text("Farklı günlerde aldığın benzer notlar tek başlık altında toplansın.",color=MaterialTheme.colorScheme.onSurfaceVariant)}}};item{Section("Konular","${t.size} başlık")};if(t.isEmpty())item{Empty("Henüz konu yok","İlk notundan sonra konu hafızası oluşmaya başlayacak.")}else items(t,key={it.id}){x->Card(onClick={open(x.id)},shape=RoundedCornerShape(22.dp),colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surface)){Row(Modifier.padding(17.dp),verticalAlignment=Alignment.CenterVertically){Surface(shape=RoundedCornerShape(15.dp),color=MaterialTheme.colorScheme.secondaryContainer){Icon(Icons.Rounded.Folder,null,Modifier.padding(11.dp).size(22.dp),tint=MaterialTheme.colorScheme.secondary)};Spacer(Modifier.width(13.dp));Column(Modifier.weight(1f)){Text(x.title,fontWeight=FontWeight.SemiBold);Text("${db.countItemsInTopic(x.id)} kayıt • otomatik ${if(x.autoGroup)"açık" else "kapalı"}",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant)};Icon(Icons.Rounded.ChevronRight,null)}}}}}
@Composable fun TopicPage(t:Db.Topic?,data:List<Db.Item>,open:(Db.Item)->Unit,m:Modifier){LazyColumn(m.fillMaxSize(),contentPadding=PaddingValues(18.dp,8.dp,18.dp,116.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Surface(shape=RoundedCornerShape(26.dp),color=MaterialTheme.colorScheme.secondaryContainer){Column(Modifier.padding(20.dp)){Text(t?.title?:"Konu",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text("Bu konunun kronolojik hafızası",color=MaterialTheme.colorScheme.onSurfaceVariant)}}};item{Section("Kayıtlar","${data.size}")};if(data.isEmpty())item{Empty("Bu konu boş","Yeni bir not veya görev ekleyebilirsin.")}else items(data,key={it.id}){if(it.type==Db.TYPE_NOTE)NoteCard(it,open)else Surface(onClick={open(it)},shape=RoundedCornerShape(20.dp),color=MaterialTheme.colorScheme.surface){Row(Modifier.padding(16.dp),verticalAlignment=Alignment.CenterVertically){Icon(if(it.status==Db.STATUS_DONE)Icons.Rounded.CheckCircle else Icons.Rounded.RadioButtonUnchecked,null,tint=if(it.status==Db.STATUS_DONE)Color(0xFF24A66A)else MaterialTheme.colorScheme.primary);Spacer(Modifier.width(12.dp));Column{Text(it.title,fontWeight=FontWeight.SemiBold);Text(it.dayKey+(if(it.dueAt>0)" • ${time(it.dueAt)}" else ""),style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant)}}}}}}
@Composable fun SearchPage(q:String,set:(String)->Unit,r:List<Db.Item>,open:(Db.Item)->Unit,m:Modifier){LazyColumn(m.fillMaxSize(),contentPadding=PaddingValues(18.dp,8.dp,18.dp,116.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{OutlinedTextField(q,set,Modifier.fillMaxWidth(),singleLine=true,leadingIcon={Icon(Icons.Rounded.Search,null)},trailingIcon={if(q.isNotEmpty())IconButton({set("")}){Icon(Icons.Rounded.Close,null)}},placeholder={Text("Görev, not veya konu ara")},shape=RoundedCornerShape(22.dp))};item{Section(if(q.isBlank())"Hızlı bul" else "Sonuçlar",if(q.isBlank())"Geçmişin tamamı" else "${r.size} kayıt")};if(q.isBlank())item{Empty("Her şeyi bulabilirsin","Bir kelime yaz; görev ve not içeriklerinde de arama yapılır.")}else if(r.isEmpty())item{Empty("Sonuç yok","Daha genel bir kelimeyle tekrar dene.")}else items(r,key={it.id}){if(it.type==Db.TYPE_NOTE)NoteCard(it,open)else Surface(onClick={open(it)},shape=RoundedCornerShape(20.dp),color=MaterialTheme.colorScheme.surface){Row(Modifier.padding(16.dp)){Icon(if(it.status==Db.STATUS_DONE)Icons.Rounded.CheckCircle else Icons.Rounded.RadioButtonUnchecked,null);Spacer(Modifier.width(12.dp));Column{Text(it.title,fontWeight=FontWeight.SemiBold);Text(it.dayKey,color=MaterialTheme.colorScheme.onSurfaceVariant,style=MaterialTheme.typography.bodySmall)}}}}}}

@OptIn(ExperimentalMaterial3Api::class)
@Composable fun AddSheet(close:()->Unit,quick:()->Unit,task:()->Unit,note:()->Unit,voiceTask:()->Unit,voiceNote:()->Unit){ModalBottomSheet(onDismissRequest=close){Column(Modifier.fillMaxWidth().padding(horizontal=20.dp).padding(bottom=28.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Text("Hızlı ekle",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text("Aklındakini en az dokunuşla kaydet.",color=MaterialTheme.colorScheme.onSurfaceVariant);option(Icons.Rounded.AutoAwesome,"Akıllı görev","Doğal dille tarih, saat ve süre yaz",quick);option(Icons.Rounded.Today,"Ayrıntılı görev","Tarih, saat, süre, tekrar ve öncelik",task);option(Icons.Rounded.Notes,"Not","Bilgi, fikir veya kayıt",note);option(Icons.Rounded.KeyboardVoice,"Sesle görev","Konuşarak görev oluştur",voiceTask);option(Icons.Rounded.Mic,"Sesli not","Konuş ve konu hafızasına kaydet",voiceNote)}}}
@Composable fun option(i:ImageVector,t:String,s:String,on:()->Unit){Surface(onClick=on,shape=RoundedCornerShape(20.dp),color=MaterialTheme.colorScheme.surfaceVariant.copy(alpha=.7f)){Row(Modifier.padding(16.dp),verticalAlignment=Alignment.CenterVertically){Surface(shape=RoundedCornerShape(14.dp),color=MaterialTheme.colorScheme.primaryContainer){Icon(i,null,Modifier.padding(10.dp).size(22.dp),tint=MaterialTheme.colorScheme.primary)};Spacer(Modifier.width(14.dp));Column{Text(t,fontWeight=FontWeight.SemiBold);Text(s,style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant)}}}}
@Composable fun QuickDialog(d:LocalDate,close:()->Unit,save:(NaturalLanguageParser.ParsedTask)->Unit){var txt by remember{mutableStateOf("")};val p=remember(txt){if(txt.isBlank())null else NaturalLanguageParser.parse(txt,d)};AlertDialog(close,title={Text("Akıllı görev")},text={Column(verticalArrangement=Arrangement.spacedBy(12.dp)){OutlinedTextField(txt,{txt=it},Modifier.fillMaxWidth(),label={Text("Doğal dille yaz")},placeholder={Text("Yarın 14:30 Ahmet'i ara 30 dk")},minLines=3,shape=RoundedCornerShape(18.dp));if(p!=null)Surface(shape=RoundedCornerShape(18.dp),color=MaterialTheme.colorScheme.primaryContainer){Column(Modifier.padding(14.dp)){Text(p.title,fontWeight=FontWeight.SemiBold);Text(p.dayKey+(if(p.dueAt>0)" • ${time(p.dueAt)}" else ""))}}}},confirmButton={Button({p?.let(save)},enabled=p!=null){Text("Ekle")}},dismissButton={TextButton(close){Text("Vazgeç")}})}
@Composable fun TaskDialog(i:Db.Item?,base:LocalDate,a:PremiumMainActivity,close:()->Unit,save:(String,String,LocalDate,LocalTime?,Int,String,Int)->Unit){var title by remember{mutableStateOf(i?.title.orEmpty())};var body by remember{mutableStateOf(i?.body.orEmpty())};var day by remember{mutableStateOf(i?.dayKey?.let{runCatching{LocalDate.parse(it)}.getOrNull()}?:base)};var tm by remember{mutableStateOf(i?.dueAt?.takeIf{it>0}?.let{Instant.ofEpochMilli(it).atZone(ZoneId.systemDefault()).toLocalTime()})};var dur by remember{mutableIntStateOf(i?.durationMinutes?:30)};var rec by remember{mutableStateOf(i?.recurrence.orEmpty())};var pri by remember{mutableIntStateOf(i?.priority?:2)};AlertDialog(close,title={Text(if(i==null)"Yeni görev" else "Görevi düzenle")},text={LazyColumn(Modifier.height(500.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{OutlinedTextField(title,{title=it},Modifier.fillMaxWidth(),label={Text("Görev")},shape=RoundedCornerShape(18.dp))};item{OutlinedTextField(body,{body=it},Modifier.fillMaxWidth(),label={Text("Açıklama")},minLines=2,shape=RoundedCornerShape(18.dp))};item{Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){OutlinedButton({a.pickDate(day){day=it}},Modifier.weight(1f)){Text(day.format(DateTimeFormatter.ofPattern("d MMM",Locale("tr","TR"))))};OutlinedButton({a.pickTime(tm?:LocalTime.of(9,0)){tm=it}},Modifier.weight(1f)){Text(tm?.format(DateTimeFormatter.ofPattern("HH:mm"))?:"Saat")}}};item{Text("Süre",fontWeight=FontWeight.SemiBold);LazyRow(horizontalArrangement=Arrangement.spacedBy(8.dp)){items(listOf(15,30,45,60,90)){x->FilterChip(dur==x,{dur=x},{Text("$x dk")})}}};item{Text("Öncelik",fontWeight=FontWeight.SemiBold);LazyRow(horizontalArrangement=Arrangement.spacedBy(8.dp)){items(listOf(0 to "Acil",1 to "Önemli",2 to "Normal")){(x,l)->FilterChip(pri==x,{pri=x},{Text(l)})}}};item{Text("Tekrar",fontWeight=FontWeight.SemiBold);LazyRow(horizontalArrangement=Arrangement.spacedBy(8.dp)){items(listOf("" to "Yok",NaturalLanguageParser.DAILY to "Her gün",NaturalLanguageParser.WEEKDAYS to "Hafta içi",NaturalLanguageParser.WEEKLY to "Her hafta",NaturalLanguageParser.MONTHLY to "Her ay")){(x,l)->FilterChip(rec==x,{rec=x},{Text(l)})}}}}},confirmButton={Button({save(title.trim(),body.trim(),day,tm,dur,rec,pri)},enabled=title.isNotBlank()){Text("Kaydet")}},dismissButton={TextButton(close){Text("Vazgeç")}})}
@Composable fun NoteDialog(i:Db.Item?,close:()->Unit,save:(String,String)->Unit){var t by remember{mutableStateOf(i?.title.orEmpty())};var b by remember{mutableStateOf(i?.body.orEmpty())};AlertDialog(close,title={Text(if(i==null)"Yeni not" else "Notu düzenle")},text={Column(verticalArrangement=Arrangement.spacedBy(12.dp)){OutlinedTextField(t,{t=it},Modifier.fillMaxWidth(),label={Text("Başlık")},shape=RoundedCornerShape(18.dp));OutlinedTextField(b,{b=it},Modifier.fillMaxWidth(),label={Text("Not")},minLines=6,shape=RoundedCornerShape(18.dp))}},confirmButton={Button({save(t.trim(),b.trim())},enabled=t.isNotBlank()||b.isNotBlank()){Text("Kaydet")}},dismissButton={TextButton(close){Text("Vazgeç")}})}
@OptIn(ExperimentalMaterial3Api::class)
@Composable fun ItemSheet(i:Db.Item,close:()->Unit,complete:()->Unit,tomorrow:()->Unit,edit:()->Unit,delete:()->Unit){ModalBottomSheet(onDismissRequest=close){Column(Modifier.fillMaxWidth().padding(horizontal=22.dp).padding(bottom=30.dp)){Text(i.title,style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text(i.dayKey+(if(i.dueAt>0)" • ${time(i.dueAt)}" else ""),color=MaterialTheme.colorScheme.onSurfaceVariant);if(i.body.isNotBlank()){Spacer(Modifier.height(16.dp));Text(i.body)};Spacer(Modifier.height(20.dp));if(i.type==Db.TYPE_TASK){Button(complete,Modifier.fillMaxWidth(),shape=RoundedCornerShape(16.dp)){Icon(Icons.Rounded.Check,null);Spacer(Modifier.width(8.dp));Text(if(i.status==Db.STATUS_DONE)"Tekrar aç" else "Tamamla")};Spacer(Modifier.height(8.dp));OutlinedButton(tomorrow,Modifier.fillMaxWidth(),shape=RoundedCornerShape(16.dp)){Text("Yarına ertele")}};Spacer(Modifier.height(8.dp));OutlinedButton(edit,Modifier.fillMaxWidth(),shape=RoundedCornerShape(16.dp)){Icon(Icons.Rounded.Edit,null);Spacer(Modifier.width(8.dp));Text("Düzenle")};TextButton(delete,Modifier.fillMaxWidth(),colors=ButtonDefaults.textButtonColors(contentColor=MaterialTheme.colorScheme.error)){Icon(Icons.Rounded.Delete,null);Spacer(Modifier.width(8.dp));Text("Sil")}}}}

fun time(ms:Long)=Instant.ofEpochMilli(ms).atZone(ZoneId.systemDefault()).toLocalTime().format(DateTimeFormatter.ofPattern("HH:mm"))
fun priority(p:Int)=when(p){0->Color(0xFFE04B4B);1->Color(0xFFF59E0B);else->Color(0xFF5969E8)}
fun event(t:String)=when(t){"CREATED"->"Oluşturuldu";"NOTE_CREATED"->"Not alındı";"COMPLETED"->"Tamamlandı";"POSTPONED"->"Ertelendi";"MOVED_IN"->"Taşındı";"EDITED"->"Düzenlendi";"DELETED"->"Silindi";"REOPENED"->"Tekrar açıldı";"RECUR_CREATED"->"Tekrar oluşturuldu";"SCHEDULED"->"Planlandı";else->t}
fun eventColor(t:String)=when(t){"COMPLETED"->Color(0xFF24A66A);"POSTPONED","DELETED"->Color(0xFFE04B4B);"NOTE_CREATED"->Color(0xFFF59E0B);else->Color(0xFF5969E8)}
